// Piano Theory App — term/quiz data
// Symbol icons are hand-drawn in icons.js (ICONS / renderIcon), not images here.

const TOPICS = [
  {
    id:'signs', name:'Musical Signs', icon:'🎵', color:'#ff6b9d',
    items:[
      // imgonly: front=image, back=name+meaning
      {type:'imgonly', term:'Staccato', meaning:'Detached', img:'staccato'},
      {type:'imgonly', term:'Accent', meaning:'Play the note with emphasis', img:'accent'},
      {type:'imgonly', term:'Fermata', meaning:'Pause on the note / rest', img:'fermata'},
      // normal with image
      {type:'normal', term:'Crescendo', meaning:'Gradually getting louder', img:'crescendo_sign'},
      {type:'normal', term:'Decrescendo', meaning:'Gradually getting softer', img:'decrescendo_sign'},
      {type:'normal', term:'Tie', meaning:'Perform the 1st note and hold for the value of both notes', img:'tie'},
      {type:'normal', term:'Slur', meaning:'Perform the notes smoothly', img:'slur'},
      {type:'normal', term:'Repeat signs', meaning:'Repeat the passage between the signs', img:'repeat'},
      {type:'normal', term:'Common time', meaning:'4 beats per bar', img:'common_time'},
      {type:'normal', term:'Metronome mark (♩= 88)', meaning:'Play 88 crotchet beats per minute', img:'metronome'},
      {type:'normal', term:'Marcato', meaning:'Play the note with strong emphasis', img:'marcato'},
      {type:'normal', term:'Portato / Portamento', meaning:'Slightly separated', img:'mezzo_staccato'},
      {type:'normal', term:'Staccatissimo', meaning:'Very detached', img:'staccatissimo'},
      {type:'normal', term:'Tenuto', meaning:'Give the note slight pressure', img:'tenuto'},
      {type:'normal', term:'8va', meaning:'Play an octave higher', img:'ottava'},
      {type:'normal', term:'Alla breve', meaning:'With a minim beat', img:'alla_breve'},
      {type:'normal', term:'Multiple-bar rest', meaning:'Rest for the number of bars stated', img:'multi_bar_rest'},
      {type:'normal', term:'First-time bar [1.]', meaning:'Play this bar the first time through', img:'first_time_bar'},
      {type:'normal', term:'Second-time bar [2.]', meaning:'Play this bar the second time through', img:'second_time_bar'},
      {type:'normal', term:'Repeated notes', meaning:'Repeat the same note(s) as written above', img:'repeated_notes'},
      {type:'normal', term:'Repeated bars (%)', meaning:'Repeat the previous bar', img:'repeated_bars'},
      // no image
      {type:'normal', term:'Legato', meaning:'Smoothly'},
      {type:'normal', term:'da capo (D.C.)', meaning:'Repeat from the beginning'},
      {type:'normal', term:'dal segno (D.S.)', meaning:'Repeat from the sign', img:'dal_segno'},
    ]
  },
  {
    id:'dynamics', name:'Dynamics', icon:'🔊', color:'#1cb0f6',
    items:[
      {type:'normal', term:'ppp (pianississimo)', meaning:'Very very quiet', img:'ppp'},
      {type:'normal', term:'pp (pianissimo)', meaning:'Very quiet', img:'pp'},
      {type:'normal', term:'p (piano)', meaning:'Quiet', img:'p_dyn'},
      {type:'normal', term:'mp (mezzo piano)', meaning:'Moderately quiet', img:'mp'},
      {type:'normal', term:'mf (mezzo forte)', meaning:'Moderately loud', img:'mf'},
      {type:'normal', term:'f (forte)', meaning:'Loud', img:'f_dyn'},
      {type:'normal', term:'ff (fortissimo)', meaning:'Very loud', img:'ff'},
      {type:'normal', term:'fff (fortississimo)', meaning:'Very very loud', img:'fff'},
      {type:'normal', term:'fp (fortepiano)', meaning:'Loud, then immediately quiet', img:'fp'},
      {type:'normal', term:'sf, sfz (sforzando, sforzato)', meaning:'Forced, accented', img:'sfz'},
      {type:'normal', term:'crescendo (cresc.)', meaning:'Gradually getting louder', img:'crescendo_sign'},
      {type:'normal', term:'decrescendo (decresc.) / diminuendo (dim.)', meaning:'Gradually getting quieter', img:'decrescendo_sign'},
    ]
  },
  {
    id:'tempo', name:'Tempo', icon:'⏱️', color:'#ff9500',
    items:[
      {type:'lang', it:'adagio', fr:'lent', de:'langsam', meaning:'Slow'},
      {type:'lang', it:'andante', fr:'modéré', de:'', meaning:'At a medium / walking speed'},
      {type:'normal', term:'allegretto', meaning:'Fairly quick'},
      {type:'normal', term:'allegro', meaning:'Quick, lively'},
      {type:'normal', term:'andantino', meaning:'Slightly faster or slower than andante'},
      {type:'normal', term:'grave', meaning:'Very slow, solemn'},
      {type:'normal', term:'larghetto', meaning:'Rather slow, but not as slow as largo'},
      {type:'normal', term:'largo', meaning:'Slow, stately'},
      {type:'normal', term:'presto', meaning:'Fast, faster than allegro'},
      {type:'normal', term:'adagietto', meaning:'Rather slow, but faster than adagio'},
      {type:'normal', term:'a tempo', meaning:'In time (return to original speed)'},
      {type:'normal', term:'tempo comodo', meaning:'At a convenient, comfortable speed'},
      {type:'normal', term:"l'istesso tempo", meaning:'At the same speed'},
      {type:'normal', term:'doppio movimento', meaning:'Twice as fast'},
      {type:'normal', term:'con moto', meaning:'With movement'},
      {type:'normal', term:'con brio', meaning:'With vigour, lively'},
      {type:'normal', term:'rallentando (rall.)', meaning:'Gradually getting slower'},
      {type:'normal', term:'ritardando (ritard. / rit.)', meaning:'Gradually getting slower'},
      {type:'normal', term:'accelerando (accel.)', meaning:'Gradually getting quicker'},
      {type:'normal', term:'stringendo', meaning:'Gradually getting faster'},
      {type:'normal', term:'incalzando', meaning:'Getting quicker'},
      {type:'normal', term:'morendo', meaning:'Dying away (getting slower and quieter)'},
      {type:'normal', term:'calando', meaning:'Dying away (getting slower and quieter)'},
      {type:'normal', term:'perdendosi', meaning:'Dying away'},
      {type:'normal', term:'smorzando (smorz.)', meaning:'Dying away in tone and speed'},
      {type:'normal', term:'ralentir', meaning:'Slow down (French)'},
    ]
  },
  {
    id:'expression', name:'Expression', icon:'🎭', color:'#ce82ff',
    items:[
      {type:'lang', it:'e, ed', fr:'et', de:'und', meaning:'And'},
      {type:'lang', it:'con', fr:'avec', de:'mit', meaning:'With'},
      {type:'lang', it:'senza', fr:'sans', de:'ohne', meaning:'Without'},
      {type:'lang', it:'ma', fr:'mais', de:'aber', meaning:'But'},
      {type:'lang', it:'non', fr:'non', de:'nicht', meaning:'Not'},
      {type:'lang', it:'più', fr:'plus', de:'', meaning:'More'},
      {type:'lang', it:'meno', fr:'moins', de:'', meaning:'Less'},
      {type:'lang', it:'poco', fr:'peu', de:'wenig', meaning:'A little'},
      {type:'normal', term:'poco a poco', meaning:'Little by little'},
      {type:'lang', it:'molto', fr:'très', de:'sehr', meaning:'Very, much'},
      {type:'lang', it:'sempre', fr:'', de:'immer', meaning:'Always'},
      {type:'lang', it:'dolce', fr:'douce', de:'süß', meaning:'Sweet, soft'},
      {type:'lang', it:'leggiero', fr:'légèrement', de:'', meaning:'Light, nimble'},
      {type:'lang', it:'vivace, vivo', fr:'vif', de:'lebhaft', meaning:'Lively, quick'},
      {type:'lang', it:'animato', fr:'animé', de:'', meaning:'Animated'},
      {type:'lang', it:'largamente', fr:'', de:'breit', meaning:'Broadly'},
      {type:'lang', it:'triste, mesto', fr:'', de:'traurig', meaning:'Sad'},
      {type:'lang', it:'tranquillo', fr:'', de:'ruhig', meaning:'Calm, peaceful'},
      {type:'lang', it:'semplice', fr:'', de:'einfach', meaning:'Simple'},
      {type:'normal', term:'agitato', meaning:'Agitated'},
      {type:'normal', term:'espressivo (espress. / espr.)', meaning:'Expressive'},
      {type:'normal', term:'allargando', meaning:'Broadening'},
      {type:'normal', term:'affettuoso', meaning:'Tenderly'},
      {type:'normal', term:'appassionato', meaning:'With passion'},
      {type:'normal', term:'maestoso', meaning:'Majestic'},
      {type:'normal', term:'grazioso', meaning:'Graceful'},
      {type:'normal', term:'giocoso', meaning:'Playful, merry'},
      {type:'normal', term:'scherzando', meaning:'Playful, joking'},
      {type:'normal', term:'risoluto', meaning:'Bold, strong'},
      {type:'normal', term:'energico', meaning:'Energetic'},
      {type:'normal', term:'pesante', meaning:'Heavy'},
      {type:'normal', term:'marziale', meaning:'In military style'},
      {type:'normal', term:'rubato', meaning:'With some freedom of time'},
      {type:'normal', term:'cantabile', meaning:'In a singing style'},
      {type:'normal', term:'sostenuto', meaning:'Sustained'},
      {type:'normal', term:'simile (sim.)', meaning:'In the same way'},
      {type:'normal', term:'nobilmente', meaning:'Nobly'},
    ]
  },
  {
    id:'general', name:'General Terms', icon:'📖', color:'#00c9b1',
    items:[
      {type:'normal', term:'Fine', meaning:'The end'},
      {type:'normal', term:'mezzo', meaning:'Half'},
      {type:'normal', term:'moderato', meaning:'Moderately'},
      {type:'normal', term:'tempo', meaning:'Speed'},
      {type:'normal', term:'alla', meaning:'In the style of'},
      {type:'normal', term:'assai', meaning:'Very, extremely'},
      {type:'normal', term:'ben', meaning:'Well'},
      {type:'normal', term:'brio', meaning:'Vigour'},
      {type:'normal', term:'deciso', meaning:'With determination'},
      {type:'normal', term:'delicato', meaning:'Delicate'},
      {type:'normal', term:'forza', meaning:'Force'},
      {type:'normal', term:'prima, primo', meaning:'First'},
      {type:'normal', term:'ritmico', meaning:'Rhythmically'},
      {type:'normal', term:'seconda', meaning:'Second'},
      {type:'normal', term:'subito', meaning:'Suddenly'},
      {type:'normal', term:'tanto', meaning:'So much'},
      {type:'normal', term:'volta', meaning:'Time (e.g. prima volta = first time)'},
      {type:'normal', term:'amore', meaning:'Love'},
      {type:'normal', term:'anima', meaning:'Soul, spirit'},
      {type:'normal', term:'come', meaning:'Similar to, as'},
      {type:'normal', term:'facile', meaning:'Easy'},
      {type:'normal', term:'fuoco', meaning:'Fire'},
      {type:'normal', term:'giusto', meaning:'Proper, exact (tempo giusto = strict time)'},
      {type:'normal', term:'niente', meaning:'Nothing'},
      {type:'normal', term:'possibile', meaning:'Possible'},
      {type:'normal', term:'quasi', meaning:'As if, resembling'},
      {type:'normal', term:'sonoro', meaning:'Resonant'},
      {type:'normal', term:'sopra', meaning:'Above'},
      {type:'normal', term:'sotto', meaning:'Below'},
      {type:'normal', term:'sotto voce', meaning:'In an undertone'},
      {type:'normal', term:'veloce', meaning:'Swift'},
      {type:'normal', term:'voce', meaning:'Voice'},
      {type:'normal', term:'attacca', meaning:'Go straight on to the next section'},
      {type:'normal', term:'dolente', meaning:'Sad, sorrowful'},
      {type:'normal', term:'estinto', meaning:'As soft as possible'},
      {type:'normal', term:'lacrimoso', meaning:'Tearful, sad'},
      {type:'normal', term:'loco', meaning:'At normal pitch (cancels 8va)'},
      {type:'normal', term:'lunga', meaning:'Long'},
      {type:'normal', term:'lusingando', meaning:'Coaxing'},
      {type:'normal', term:'misura', meaning:'Measure'},
      {type:'normal', term:'ossia', meaning:'Or'},
      {type:'normal', term:'piacevole', meaning:'Pleasant'},
      {type:'normal', term:'piangevole', meaning:'Plaintive'},
      {type:'normal', term:'pochettino', meaning:'A very little'},
      {type:'normal', term:'teneramente', meaning:'Tenderly'},
      {type:'normal', term:'tosto', meaning:'Swift, rapid'},
      {type:'normal', term:'volante', meaning:'Flying, fast'},
      {type:'normal', term:'rf, rfz rinforzando (rinf.)', meaning:'Reinforcing'},
      {type:'normal', term:'una corda', meaning:'Press the left (soft) pedal'},
      {type:'normal', term:'tre corde', meaning:'Release the left pedal'},
      {type:'normal', term:'mano sinistra (m.s.)', meaning:'Left hand'},
      {type:'normal', term:'mano destra (m.d.)', meaning:'Right hand'},
      // French
      {type:'normal', term:'à', meaning:'To, at'},
      {type:'normal', term:'assez', meaning:'Enough'},
      {type:'normal', term:'cédez', meaning:'Relax the speed'},
      {type:'normal', term:'en dehors', meaning:'Prominent, make the melody stand out'},
      {type:'normal', term:'presser', meaning:'Hurry'},
      {type:'normal', term:'retenu', meaning:'Held back'},
      {type:'normal', term:'vite', meaning:'Quick'},
      // German
      {type:'normal', term:'Ausdruck', meaning:'Expression'},
      {type:'normal', term:'bewegt', meaning:'With movement'},
      {type:'normal', term:'etwas', meaning:'Somewhat, rather'},
      {type:'normal', term:'fröhlich', meaning:'Cheerful'},
      {type:'normal', term:'schnell', meaning:'Fast'},
      {type:'normal', term:'voll', meaning:'Full'},
      {type:'normal', term:'wieder', meaning:'Again'},
      {type:'normal', term:'zart', meaning:'Tender'},
      {type:'normal', term:'zu', meaning:'To'},
    ]
  }
];

// ══════════ MUSIC INSTRUMENT module ══════════
// Sourced from ABRSM Grade 1-5 cumulative orchestral-instrument knowledge:
// family (how the sound is produced), clef(s) used, and transposing instruments.
const INSTRUMENT_TOPICS = [
  {
    id:'strings', name:'Strings', icon:'🎻', color:'#ff6b9d',
    items:[
      {type:'normal', term:'Violin', meaning:'String family, played with a bow. Treble clef.', photo:'images/violin.png'},
      {type:'normal', term:'Viola', meaning:'String family, played with a bow. Alto clef.', photo:'images/viola.jpg'},
      {type:'normal', term:'Cello', meaning:'String family, played with a bow. Bass clef (also alto/treble for high passages).', photo:'images/cello.jpg'},
      {type:'normal', term:'Double bass', meaning:'String family, played with a bow. Bass clef. Sounds an octave lower than written.', photo:'images/double_bass.jpg'},
      {type:'normal', term:'Harp', meaning:'String family, plucked rather than bowed.', photo:'images/harp.jpg'},
    ]
  },
  {
    id:'woodwind', name:'Woodwind', icon:'🎶', color:'#1cb0f6',
    items:[
      {type:'normal', term:'Flute', meaning:'Woodwind family, no reed. Treble clef.', photo:'images/flute.jpg'},
      {type:'normal', term:'Piccolo', meaning:'Woodwind family, no reed (a smaller, higher-pitched flute). Treble clef. Sounds an octave higher than written.', photo:'images/piccolo.jpg'},
      {type:'normal', term:'Oboe', meaning:'Woodwind family, double reed. Treble clef.', photo:'images/oboe.jpg'},
      {type:'normal', term:'Cor anglais', meaning:'Woodwind family, double reed (a lower-pitched oboe). Treble clef.', photo:'images/cor_anglais.jpg'},
      {type:'normal', term:'Clarinet', meaning:'Woodwind family, single reed. Treble clef. A transposing instrument.', photo:'images/clarinet.jpg'},
      {type:'normal', term:'Bass clarinet', meaning:'Woodwind family, single reed. Lower-pitched than the clarinet.', photo:'images/bass_clarinet.jpg'},
      {type:'normal', term:'Bassoon', meaning:'Woodwind family, double reed. Bass clef (also alto/treble for high passages).', photo:'images/bassoon.jpg'},
      {type:'normal', term:'Double bassoon', meaning:'Woodwind family, double reed. Sounds an octave lower than the bassoon.', photo:'images/double_bassoon.jpg'},
      {type:'normal', term:'Saxophone', meaning:'Woodwind family, single reed. Not part of the standard orchestra.', photo:'images/saxophone.jpg'},
    ]
  },
  {
    id:'brass', name:'Brass', icon:'🎺', color:'#ff9500',
    items:[
      {type:'normal', term:'Trumpet (in B♭)', meaning:'Brass family. Treble clef. A transposing instrument — sounds a tone lower than written.', photo:'images/trumpet.jpg'},
      {type:'normal', term:'Cornet', meaning:'Brass family. Treble clef. Similar to the trumpet but with a mellower tone.', photo:'images/cornet.png'},
      {type:'normal', term:'Horn in F', meaning:'Brass family. Treble or bass clef. A transposing instrument — sounds a 5th lower than written.', photo:'images/horn.png'},
      {type:'normal', term:'Trombone', meaning:'Brass family. Bass clef (tenor trombone also reads alto/treble clef). Uses a slide instead of valves.', photo:'images/trombone.jpg'},
      {type:'normal', term:'Tuba', meaning:'Brass family. Bass clef. The lowest-pitched brass instrument.', photo:'images/tuba.jpg'},
    ]
  },
  {
    id:'percussion', name:'Percussion', icon:'🥁', color:'#ce82ff',
    items:[
      {type:'normal', term:'Timpani', meaning:'Pitched percussion — tuned drums. A standard orchestra usually has 2, each tuned to a different pitch.', photo:'images/timpani.jpg'},
      {type:'normal', term:'Xylophone', meaning:'Pitched percussion — wooden bars struck with mallets.', photo:'images/xylophone.jpg'},
      {type:'normal', term:'Glockenspiel', meaning:'Pitched percussion — metal bars struck with mallets.', photo:'images/glockenspiel.jpg'},
      {type:'normal', term:'Side drum', meaning:'Unpitched percussion (also called the snare drum).', photo:'images/side_drum.jpg'},
      {type:'normal', term:'Bass drum', meaning:'Unpitched percussion — the largest orchestral drum.', photo:'images/bass_drum.jpg'},
      {type:'normal', term:'Triangle', meaning:'Unpitched percussion — a metal triangle struck with a beater.', photo:'images/triangle.jpg'},
      {type:'normal', term:'Cymbals', meaning:'Unpitched percussion — two metal discs clashed together.', photo:'images/cymbals.jpg'},
      {type:'normal', term:'Tambourine', meaning:'Unpitched percussion — a frame drum with metal jingles.', photo:'images/tambourine.jpg'},
    ]
  },
  {
    id:'voice', name:'Voice', icon:'🎤', color:'#00c9b1',
    items:[
      {type:'normal', term:'Soprano', meaning:'The highest female voice.', emoji:'🎤'},
      {type:'normal', term:'Mezzo-soprano', meaning:'Female voice between soprano and alto.', emoji:'🎤'},
      {type:'normal', term:'Contralto (Alto)', meaning:'The lowest female voice.', emoji:'🎤'},
      {type:'normal', term:'Counter-tenor', meaning:'The highest male voice, in the range of alto/mezzo-soprano.', emoji:'🎤'},
      {type:'normal', term:'Tenor', meaning:'A high male voice.', emoji:'🎤'},
      {type:'normal', term:'Baritone', meaning:'Male voice between tenor and bass.', emoji:'🎤'},
      {type:'normal', term:'Bass', meaning:'The lowest male voice.', emoji:'🎤'},
    ]
  }
];

